/**
 * This code was AUTOGENERATED using the solana-codegen-cpp library.
 * Please DO NOT EDIT THIS FILE, instead use visitors to add features,
 * then rerun solana-codegen-cpp to update it.
 *
 * @see https://github.com/etodanik/solana-codegen-cpp
 */

#include "SolanaProgram.h"

#define LOCTEXT_NAMESPACE "FSolanaProgramModule"

void FSolanaProgramModule::StartupModule() {}

void FSolanaProgramModule::ShutdownModule() {}

#undef LOCTEXT_NAMESPACE

IMPLEMENT_MODULE(FSolanaProgramModule, SolanaProgram)
