/**
 * This code was AUTOGENERATED using the solana-codegen-cpp library.
 * Please DO NOT EDIT THIS FILE, instead use visitors to add features,
 * then rerun solana-codegen-cpp to update it.
 *
 * @see https://github.com/etodanik/solana-codegen-cpp
 */

#pragma once

#include "Solana/AccountMeta.h"
#include "Solana/Instruction.h"
#include "Solana/PublicKey.h"
#include "SolanaProgram/Programs.h"
#include "Borsh/Borsh.h"

// Accounts.
struct FInitializeAccounts
{
	FAccountMeta NewGameDataAccount;
	FAccountMeta Signer;
	FAccountMeta SystemProgram;
};

struct FInitializeInstructionData
{
	uint8 Discriminator[8] = { 175, 175, 109, 31, 13, 152, 155, 237 };
};

inline auto serialize(FInitializeInstructionData& Data, borsh::Serializer& Serializer) { return Serializer(Data.Discriminator); }

struct FInitializeInstruction : FInstruction
{
	FInitializeInstruction(FPublicKey InNewGameDataAccount, FPublicKey InSigner, FPublicKey InSystemProgram)
	{
		ProgramId = GTinyAdventureID;
		Accounts.Add(FAccountMeta(InNewGameDataAccount, false, true));
		Accounts.Add(FAccountMeta(InSigner, true, true));
		Accounts.Add(FAccountMeta(InSystemProgram, false, false));
		Accounts.Add(FAccountMeta(GTinyAdventureID, false, false));
		FInitializeInstructionData InstructionData;
		Data = BorshSerialize(InstructionData);
	}
};
