/**
 * This code was AUTOGENERATED using the solana-codegen-cpp library.
 * Please DO NOT EDIT THIS FILE, instead use visitors to add features,
 * then rerun solana-codegen-cpp to update it.
 *
 * @see https://github.com/etodanik/solana-codegen-cpp
 */

#pragma once

#include "Solana/AccountMeta.h"
#include "Solana/Instruction.h"
#include "Solana/PublicKey.h"
#include "SolanaProgram/Programs.h"
#include "Borsh/Borsh.h"

// Accounts.
struct FMoveLeftAccounts
{
	FAccountMeta GameDataAccount;
};

struct FMoveLeftInstructionData
{
	uint8 Discriminator[8] = { 45, 212, 186, 188, 248, 238, 45, 99 };
};

inline auto serialize(FMoveLeftInstructionData& Data, borsh::Serializer& Serializer) { return Serializer(Data.Discriminator); }

struct FMoveLeftInstruction : FInstruction
{
	FMoveLeftInstruction(FPublicKey InGameDataAccount)
	{
		ProgramId = GTinyAdventureID;
		Accounts.Add(FAccountMeta(InGameDataAccount, false, true));
		Accounts.Add(FAccountMeta(GTinyAdventureID, false, false));
		FMoveLeftInstructionData InstructionData;
		Data = BorshSerialize(InstructionData);
	}
};
