/**
 * This code was AUTOGENERATED using the solana-codegen-cpp library.
 * Please DO NOT EDIT THIS FILE, instead use visitors to add features,
 * then rerun solana-codegen-cpp to update it.
 *
 * @see https://github.com/etodanik/solana-codegen-cpp
 */

#pragma once

#include "Containers/StaticArray.h"
#include "Solana/AccountMeta.h"
#include "Solana/Instruction.h"
#include "Solana/PublicKey.h"
#include "SolanaProgram/Programs.h"
#include "Borsh/Borsh.h"

// Accounts.
struct MoveRightAccounts
{
	FAccountMeta GameDataAccount;
};

struct MoveRightInstructionData
{
	TStaticArray<uint8, 8> Discriminator = { 201, 13, 149, 180, 220, 208, 135, 152 };
};

inline auto serialize(MoveRightInstructionData& Data, borsh::Serializer& Serializer) { return Serializer(Data.Discriminator); }

struct MoveRightInstruction : FInstruction
{
	MoveRightInstruction(FPublicKey GameDataAccount)
	{
		ProgramId = GTinyAdventureID;
		Accounts.Add(FAccountMeta(GameDataAccount, true, false));
		MoveRightInstructionData Data;
		TArray<uint8_t>			 SerializedData = BorshSerialize(Data);
	}
};
