/**
 * This code was AUTOGENERATED using the solana-codegen-cpp library.
 * Please DO NOT EDIT THIS FILE, instead use visitors to add features,
 * then rerun solana-codegen-cpp to update it.
 *
 * @see https://github.com/etodanik/solana-codegen-cpp
 */

#pragma once

#include "Solana/AccountMeta.h"
#include "Solana/Instruction.h"
#include "Solana/PublicKey.h"
#include "SolanaProgram/Programs.h"
#include "Borsh/Borsh.h"

// Accounts.
struct FMoveRightAccounts
{
	FAccountMeta GameDataAccount;
};

struct FMoveRightInstructionData
{
	uint8 Discriminator[8] = { 201, 13, 149, 180, 220, 208, 135, 152 };
};

inline auto serialize(FMoveRightInstructionData& Data, borsh::Serializer& Serializer) { return Serializer(Data.Discriminator); }

struct FMoveRightInstruction : FInstruction
{
	FMoveRightInstruction(FPublicKey InGameDataAccount)
	{
		ProgramId = GTinyAdventureID;
		Accounts.Add(FAccountMeta(InGameDataAccount, false, true));
		Accounts.Add(FAccountMeta(GTinyAdventureID, false, false));
		FMoveRightInstructionData InstructionData;
		Data = BorshSerialize(InstructionData);
	}
};
