/**
 * This code was AUTOGENERATED using the solana-codegen-cpp library.
 * Please DO NOT EDIT THIS FILE, instead use visitors to add features,
 * then rerun solana-codegen-cpp to update it.
 *
 * @see https://github.com/etodanik/solana-codegen-cpp
 */

struct FGameDataAccount
{
	uint8 Discriminator[8];
	uint8 PlayerPositionundefined;
};
