/**
 * This code was AUTOGENERATED using the solana-codegen-cpp library.
 * Please DO NOT EDIT THIS FILE, instead use visitors to add features,
 * then rerun solana-codegen-cpp to update it.
 *
 * @see https://github.com/etodanik/solana-codegen-cpp
 */

#pragma once

#include "Solana/PublicKey.h"

// `TINY_ADVENTURE` program ID.
const FPublicKey GTinyAdventureID = FPublicKey(TEXT("2F2K73Sj1ygx4N9ptCegrxEDvGNLCndrsCdmUbcHej3c"));
